# Generated by Django 4.1.5 on 2023-02-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create',
            new_name='created',
        ),
    ]
